version: "3.7"

services:

  postgres-production:
    container_name: 'userstarter-db-postgres'
    image: 'postgres:12.0'
    restart: always
    ports:
      - '5434:5432'
    environment:
      - 'POSTGRES_USER=username'
      - 'POSTGRES_DB=userstarter'
      - 'POSTGRES_PASSWORD=password'
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

  postgres-test:
    container_name: 'userstarter-db-test'
    image: 'postgres:12.0'
    restart: always
    ports:
      - '5435:5432'
    environment:
      - 'POSTGRES_USER=username'
      - 'POSTGRES_DB=userstarter-test'
      - 'POSTGRES_PASSWORD=password'

  maildev:
      image: maildev/maildev
      restart: always
      environment:
        - TZ=Asia/Shanghai
        - MAILDEV_WEB_PORT=1080
        - MAILDEV_SMTP_PORT=1025
      ports:
        - "8080:1080"
        - "8025:1025"
      logging:
        driver: "json-file"
        options:
          max-size: "1m"

volumes:
  postgres_prod_data:
